name: Deploy to Production

on:
  push:
    branches: [ main, surface-detection ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          cd server && npm install && cd ..

      - name: Build
        run: |
          SKIP_TYPESCRIPT=true npm run build
          cd server && SKIP_TYPESCRIPT=true npm run build && cd ..

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 170.64.223.56
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/lutruwita2
            git pull
            npm install
            SKIP_TYPESCRIPT=true npm run build
            cd server && npm install && SKIP_TYPESCRIPT=true npm run build && cd ..
            # Copy environment variables for backend
            cp .env.production server/.env
            pm2 restart all
