name: Deploy to Production

on:
  push:
    branches: [ main, surface-detection ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          cd server && npm install && cd ..

      - name: Build
        run: |
          SKIP_TYPESCRIPT=true npm run build 2>&1 || { echo "Client build failed with:"; cat npm-debug.log; exit 1; }
          cd server && SKIP_TYPESCRIPT=true npm run build 2>&1 || { echo "Server build failed with:"; cat npm-debug.log; exit 1; } && cd ..

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SERVER_PASS: ${{ secrets.SERVER_PASS }}
        run: |
          sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no root@170.64.223.56 '
            cd /var/www/lutruwita2
            git pull
            npm install
            SKIP_TYPESCRIPT=true npm run build
            cd server && npm install && SKIP_TYPESCRIPT=true npm run build && cd ..
            cp .env.production server/.env
            pm2 restart all
          '
